# Generated by Django 5.1.6 on 2025-02-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.CharField(max_length=50, unique=True)),
                ('order_payment_ID', models.CharField(max_length=50, unique=True)),
                ('order_status', models.CharField(max_length=20)),
                ('order_quantity', models.IntegerField()),
                ('order_freight_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_freight_service', models.CharField(choices=[('PAC', 'PAC'), ('SEDEX', 'SEDEX'), ('PACMINI', 'PACMINI'), ('JADLOG', 'JADLOG')], max_length=50)),
                ('order_zip_code', models.CharField(max_length=8)),
                ('order_street', models.CharField(max_length=255)),
                ('order_neighborhood', models.CharField(max_length=255)),
                ('order_city', models.CharField(max_length=255)),
                ('order_state', models.CharField(max_length=2)),
                ('order_house_number', models.CharField(max_length=20)),
                ('order_complement', models.CharField(blank=True, max_length=255, null=True)),
                ('order_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('order_updated_at', models.DateTimeField(auto_now=True)),
                ('order_is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
